// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsJ-neWbYpRcBslQbJxAn9FOSQp5jR0Bk',
    appId: '1:132010059086:web:7705b1e975abb24ca5aa1f',
    messagingSenderId: '132010059086',
    projectId: 'osh-monitor',
    authDomain: 'osh-monitor.firebaseapp.com',
    databaseURL: 'https://osh-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'osh-monitor.firebasestorage.app',
    measurementId: 'G-QBWG8YV6ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktoV5pJPKYZjk26LNeV6X4v1r09sRvsA',
    appId: '1:132010059086:android:97b00e7a82f6f14fa5aa1f',
    messagingSenderId: '132010059086',
    projectId: 'osh-monitor',
    databaseURL: 'https://osh-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'osh-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0YgtIlw1PuRbnobOVmQX9ce5MdfGA25k',
    appId: '1:132010059086:ios:d62d59a3b257cc8ca5aa1f',
    messagingSenderId: '132010059086',
    projectId: 'osh-monitor',
    databaseURL: 'https://osh-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'osh-monitor.firebasestorage.app',
    androidClientId: '132010059086-ch05bd4apv603lj2dhoal3162dgl346h.apps.googleusercontent.com',
    iosClientId: '132010059086-d8vgsaq4tbi2h0p670pi1of9nbb5ob83.apps.googleusercontent.com',
    iosBundleId: 'com.example.osh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0YgtIlw1PuRbnobOVmQX9ce5MdfGA25k',
    appId: '1:132010059086:ios:d62d59a3b257cc8ca5aa1f',
    messagingSenderId: '132010059086',
    projectId: 'osh-monitor',
    databaseURL: 'https://osh-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'osh-monitor.firebasestorage.app',
    androidClientId: '132010059086-ch05bd4apv603lj2dhoal3162dgl346h.apps.googleusercontent.com',
    iosClientId: '132010059086-d8vgsaq4tbi2h0p670pi1of9nbb5ob83.apps.googleusercontent.com',
    iosBundleId: 'com.example.osh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsJ-neWbYpRcBslQbJxAn9FOSQp5jR0Bk',
    appId: '1:132010059086:web:b8848a5cfff1fcfaa5aa1f',
    messagingSenderId: '132010059086',
    projectId: 'osh-monitor',
    authDomain: 'osh-monitor.firebaseapp.com',
    databaseURL: 'https://osh-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'osh-monitor.firebasestorage.app',
    measurementId: 'G-9GWRVLVN6D',
  );

}